name: Integration

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: oracle
          java-version: 21
          cache: maven
          cache-dependency-path: pom.xml

      - name: Provide Permissions
        run: chmod +x ./mvnw

      - name: Compile
        run: ./mvnw compile

      - name: Test
        run: ./mvnw test

      - name: Package
        run: ./mvnw clean package

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: quarkus package
          path: target/
